"""Static ATen op-census rules for the equivalent computation graph (Profiling v2 P1).

This module restores the ORIGINAL goal of the profiling tools: given a prompt,
produce the workflow's equivalent computation graph - the sequence of base
(ATen) operators each node really runs - WITHOUT executing any node code.

Where the census comes from
---------------------------
``comfy/profiling/opgraph.py`` probes nodes by *really executing* them (P0
gated that behind the dangerous-mode flag after a 1MB input wedged the
backend).  The offline sampler (``comfy/profiling/sampler.py``) runs that same
probe once per registered node on standard tiny inputs and freezes the
resulting ATen op census into a static rules JSON - ``data/op_rules.json`` -
which ships with the repository and can be regenerated by CI whenever the node
registry evolves.  At Analyze time the assembler (``assemble_workflow`` in
``opgraph.py``) looks rules up here instead of executing anything.

Rule entry schema (one entry per class_type)
--------------------------------------------
::

    {
      "source": "offline_probe" | "manual",
      "flops_from_shape": "estimated" | "params_driven" | "unknown",
      "notes": "optional human note",
      "probes": [
        {
          "input_signature": {"<input>": "<desc>", ...},
          "ops": [{"op": "aten.mm.default", "count": 2, "flops": 123}],
          "ops_total": 2, "data_dependent_reads": 0, "probe_ms": 12
        }
      ]
    }

Honest boundaries
-----------------
* The census is a *structure* (which operators, how many calls).  The per-op
  FLOPs recorded in a probe entry are those of the SAMPLE inputs - they do not
  extrapolate to other shapes and the assembler must not present them as the
  node's real FLOPs; per-node FLOPs at Analyze time stay the job of the M2
  shape-aware formula ledger (``estimators.py``), merged in by the assembler.
* Nodes without a rule are honestly reported as missing (the rule library is
  allowed to be incomplete - the coverage report says so instead of guessing).
* stdlib-only besides the rest of ``comfy.profiling``: importing this module
  must not import torch or nodes.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any, Dict, Optional

logger = logging.getLogger(__name__)

#: Version of the rules JSON document (independent of the report versions).
OPRULES_VERSION = 1

#: The shipped rules file.  Generated by ``comfy.profiling.sampler`` (offline),
#: reviewed by hand, and regenerated when the node registry grows.
_DATA_PATH = Path(__file__).resolve().parent / "data" / "op_rules.json"

_rules: Optional[Dict[str, Any]] = None
_rules_path: Optional[Path] = None

#: Coverage buckets reported per node (and aggregated in ``coverage_summary``).
#: * covered       - a rule exists: the node's op census is known statically;
#: * params_driven - no census, but the M2 ledger has a params-driven formula;
#: * unknown       - M2 estimator exists but its FLOPs status is "unknown";
#: * missing       - neither a rule nor an M2 estimator: no information.
COVERAGE_BUCKETS = ("covered", "params_driven", "unknown", "missing")


def load_rules(path: Optional[Path] = None, force: bool = False) -> Dict[str, Any]:
    """Load (and memoize) the shipped rules document.

    Tolerant by contract: a missing or corrupt file yields an empty ruleset -
    the coverage report then says "missing" for everything instead of raising,
    exactly like the M1/M2 engines treat unregistered nodes.
    """
    global _rules, _rules_path
    # Memoize semantics: a no-argument call returns whatever is already loaded
    # (the sampler/tests install documents via set_rules/load_rules(path) and
    # later lookups must see them); an explicit path only bypasses the cache
    # when it differs from the loaded one or force is set.
    if not force and path is None and _rules is not None:
        return _rules
    load_path = Path(path) if path is not None else _DATA_PATH
    if not force and _rules is not None and _rules_path == load_path:
        return _rules
    path = load_path
    try:
        with open(path, "r", encoding="utf-8") as fh:
            doc = json.load(fh)
        if not isinstance(doc, dict) or doc.get("version") != OPRULES_VERSION:
            raise ValueError(f"unsupported op_rules document: version={doc!r}")
        rules = doc.get("rules")
        if not isinstance(rules, dict):
            raise ValueError("op_rules document has no 'rules' mapping")
        _rules = doc
        logger.info("opgraph rules: %d entries from %s", len(rules), path.name)
    except FileNotFoundError:
        logger.info("opgraph rules: none shipped (%s not found) - coverage is empty", path.name)
        _rules = {"version": OPRULES_VERSION, "rules": {}}
    except Exception as exc:  # noqa: BLE001 - a corrupt rule file must not
        # take the panel down; empty ruleset + honest coverage instead.
        logger.warning("opgraph rules: failed to load %s (%s) - treating as empty", path, exc)
        _rules = {"version": OPRULES_VERSION, "rules": {}}
    _rules_path = path
    return _rules


def set_rules(doc: Dict[str, Any], path: Optional[Path] = None) -> None:
    """Install a rules document in memory (tests, the sampler)."""
    global _rules, _rules_path
    _rules = doc
    _rules_path = Path(path) if path is not None else _rules_path


def rule_for(class_type: str) -> Optional[Dict[str, Any]]:
    """The rule entry for ``class_type`` (None = no rule, honestly missing)."""
    doc = load_rules()
    entry = doc["rules"].get(class_type)
    return entry if isinstance(entry, dict) else None


def census_for(class_type: str) -> Optional[list]:
    """The first probe census for a node: list of {op, count, flops}.

    An EMPTY list is a valid result - it means the node's execute runs zero
    ATen operators (a pure-Python leaf, e.g. ``TextVocabBuild``); the rule
    exists and the equivalent graph shows a leaf, not a gap.  ``None`` means
    no rule at all.
    """
    entry = rule_for(class_type)
    if not entry:
        return None
    probes = entry.get("probes") or []
    for probe in probes:
        ops = probe.get("ops")
        if isinstance(ops, list):
            return ops
    return None


def data_dependent_reads_for(class_type: str) -> int:
    """The canned-read count recorded by the rule's first probe (0 if none)."""
    entry = rule_for(class_type)
    if not entry:
        return 0
    probes = entry.get("probes") or []
    for probe in probes:
        if isinstance(probe.get("ops"), list):
            return int(probe.get("data_dependent_reads") or 0)
    return 0


def coverage_for(class_type: str, m2_flops_status: Optional[str] = None,
                 m2_estimated: bool = False) -> str:
    """Which coverage bucket a node falls into (see ``COVERAGE_BUCKETS``).

    ``m2_estimated`` is True when the M2 ledger produced a real estimate for
    the node (estimator present and not "unknown"); ``m2_flops_status`` is the
    ledger's flops_status ("estimated"|"zero"|"unknown"|None).
    """
    if rule_for(class_type) is not None:
        return "covered"
    # "zero" means the M2 ledger PROVED the node runs no FLOPs-carrying ops
    # (pure pass-through / pure python) - a deterministic formula answer, not
    # a gap; it shares the params_driven bucket ("formula layer knows").
    if m2_estimated and m2_flops_status in ("estimated", "zero"):
        return "params_driven"
    if m2_estimated:
        return "unknown"
    return "missing"


def coverage_summary(buckets: Dict[str, str]) -> Dict[str, int]:
    """Aggregate per-node coverage bucket strings into the report counters."""
    out = {name: 0 for name in COVERAGE_BUCKETS}
    for bucket in buckets.values():
        if bucket in out:
            out[bucket] += 1
    return out


def stats() -> Dict[str, Any]:
    """Quick library overview for logs and the coverage report."""
    doc = load_rules()
    rules = doc["rules"]
    by_source: Dict[str, int] = {}
    for entry in rules.values():
        source = str(entry.get("source") or "unknown")
        by_source[source] = by_source.get(source, 0) + 1
    return {
        "version": doc.get("version"),
        "entries": len(rules),
        "by_source": by_source,
        "path": str(_rules_path or _DATA_PATH),
    }
